services:
  postgres:
    image: postgres:15
    container_name: wms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: awk2osq
      POSTGRES_DB: wms
    ports:
      - "35432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: wms-redis
    restart: unless-stopped
    ports:
      - "36379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
